export enum StatusOnboarding {
  LOAD_NAMES = 'LOAD_NAMES',
  IDENTITY_DOCUMENT = 'IDENTITY_DOCUMENT',
  ADDRESS = 'ADDRESS',
  HOUSING = 'HOUSING',
  EDUCATION = 'EDUCATION',
  OCCUPATION = 'OCCUPATION',
  COMPANY = 'COMPANY',
  CONTACT = 'CONTACT',
  COMPLETED = 'COMPLETED',
}
